site_name: kmerkit (UNDER ACTIVE DEVELOPMENT)

repo_url: https://github.com/eaton-lab/kmerkit

theme:
  name: material
  palette:
    - scheme: slate
      primary: teal     
      accent: orange
      toggle:
        icon: material/lightbulb
        name: Switch to light mode
    - scheme: default
      primary: teal     
      accent: orange
      toggle:
        icon: material/lightbulb-outline
        name: Switch to dark mode
  icon:
    logo: octicons/hubot-24
  features:
    - navigation.instant
    - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky

nav:
  - Home: index.md
  - About/Ethos: ethos.md
  - Installation: installation.md
  - Tutorial - User Guide:
      - Quick-start: quick-start.md
      - kinit - start a project: kinit.md
      - ktrim - read trim/filter: kfilter.md  
      - kcount - counting kmers: kcount.md
      - kfilter - select target kmers: kfilter.md
      - kextract - select target reads: kfilter.md
      - kmatrix - export genotypes: kmatrix.md
      - kgwas - GWAS inference: kmatrix.md
  - Cookbooks:
      - GWAS WGS sex-determination (Amaranth): cookbooks/1-amaranthus-dioecy.md
      # - Amaranth-dioecy (API): cookbooks/1-amaranthus-dioecy-api.md
      - GWAS WGS many traits (Arabidopsis): cookbooks/2-arabidopsis-gwas.md
      - GWAS RAD-seq: cookbooks/3-pedicularis-RAD-gwas.md

markdown_extensions:
  - toc:
      toc_depth: 4
  - markdown.extensions.codehilite:
      guess_lang: false      
  - admonition
  - codehilite
  # - extra
  - pymdownx.superfences:
      custom_fences:
      - name: mermaid
        class: mermaid
        format: !!python/name:pymdownx.superfences.fence_div_format ''
  - pymdownx.tabbed      
  - pymdownx.details
  # - pymdownx.highlight  

extra_javascript:
  - js/custom.js 
  - https://unpkg.com/mermaid@8.9.2/dist/mermaid.min.js
  # - https://cdnjs.cloudflare.com/ajax/libs/mermaid/7.0.9/mermaid.min.js
  # - js/termynal.js
  # - js/mermaid.js

extra_css:
  # - https://cdnjs.cloudflare.com/ajax/libs/mermaid/7.0.9/mermaid.neutral.css
  # - css/termynal.css
  # - css/custom.css
